import type { Metadata } from "next";
import { AuthBar } from "@/widgets/auth-bar";
import { getSession } from "@/src/lib/auth/session";
import "./globals.css";

export const metadata: Metadata = {
  title: "next-prisma",
  description: "Generated by create-prisma",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body>
        {session ? <AuthBar session={session} /> : null}
        {children}
      </body>
    </html>
  );
}
