import type { Metadata } from "next";
import { AuthBar } from "@/widgets/auth-bar";
import { getSession } from "@/src/lib/auth/session";
import "./globals.css";
import { IBM_Plex_Sans, Noto_Sans } from "next/font/google";
import { cn } from "@/shared/lib/utils";
import { ThemeProvider } from "@/shared/providers/theme-provider.tsx";

const notoSansHeading = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "next-prisma",
  description: "Generated by create-prisma",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html
      lang="ru"
      suppressHydrationWarning
      className={cn(
        "font-sans",
        ibmPlexSans.variable,
        notoSansHeading.variable,
      )}
    >
      <meta name="apple-mobile-web-app-title" content="Budget" />
      <meta name="description" content="It is a simple budget tracker." />
      <title>Budget</title>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {session ? <AuthBar session={session} /> : null}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
