import type { Metadata } from "next";
import { AuthBar } from "@/widgets/auth-bar";
import { getSession } from "@/src/lib/auth/session";
import "./globals.css";
import { IBM_Plex_Sans, Noto_Sans } from "next/font/google";
import { cn } from "@/shared/lib/utils";

const notoSansHeading = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "next-prisma",
  description: "Generated by create-prisma",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html
      lang="en"
      className={cn(
        "font-sans",
        ibmPlexSans.variable,
        notoSansHeading.variable,
      )}
    >
      <body>
        {session ? <AuthBar session={session} /> : null}
        {children}
      </body>
    </html>
  );
}
